import { AntdRegistry } from '@ant-design/nextjs-registry';
import "@/styles.scss";
// import google Font
import { Josefin_Sans } from 'next/font/google';
import { ConfigProvider } from "antd";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
// font
const font = Josefin_Sans({ subsets: ['latin'] })

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={font.className}>
      <body className={font.className}>
        <ConfigProvider direction="ltr">

          <AntdRegistry>
            {children}
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  )
}
